### ISSUE TITLE
啥时候升级到maui 8.0以上哇

### ISSUE THREAD

**Issue by tutuhuai** [jingliancui/XamarinFormsAlipaySDKSample#1]
目前这个东西在maui中无法使用，特别是8.0版本以上，大佬啥时候更新一下哇

**Comment by tutuhuai** [comment]
这个ios的库，用不了

**Comment by jingliancui** [comment]
请问有错误提示吗

**Comment by tutuhuai** [comment]
> 请问有错误提示吗

![image](https://github.com/jingliancui/XamarinFormsAlipaySDKSample/assets/20356550/94bd3763-1249-4a0d-944f-0736d9fb5269)

**Comment by tutuhuai** [comment]
> 请问有错误提示吗

![image](https://github.com/jingliancui/XamarinFormsAlipaySDKSample/assets/20356550/16971a07-b6e7-4494-a01b-ce51807f1560)

**Comment by jingliancui** [comment]
我记得有个新的， 我找一下

**Comment by jingliancui** [comment]
https://mp.weixin.qq.com/s?__biz=MzUyMjMyNDkyNA==&mid=2247484497&idx=1&sn=2f2b681af7c0f2305f9fa9c6ad319956&chksm=f9ccda82cebb5394a2106f2655045666efd49a738633317a0cce317c7fb69e91c64057699d10&mpshare=1&scene=23&srcid=0719Re7GMFXcyErsglMytu2K&sharer_shareinfo=f1a8a8d4015dbcd49edba66fc0d6deae&sharer_shareinfo_first=f1a8a8d4015dbcd49edba66fc0d6deae#rd
